import SwiftUI

// 마스코트 '패시' — Figma 컴포넌트(172:1037) SVG 지오메트리 미러 (Compose PassyMascot.kt와 1:1).
// 사용 규칙: Empty State·완료·대기 상태 전용, 문제 풀이 화면 사용 금지 (디자인 시스템 §마스코트)
struct PassyMascotView: View {
    var body: some View {
        GeometryReader { geometry in
            let scale = min(geometry.size.width / 120, geometry.size.height / 132)

            ZStack {
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.839, blue: 0.369))
                    .frame(width: 10 * scale, height: 14 * scale)
                    .rotationEffect(.degrees(12))
                    .position(x: 55.4 * scale, y: 11.9 * scale)
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.839, blue: 0.369))
                    .frame(width: 8 * scale, height: 12 * scale)
                    .rotationEffect(.degrees(-14))
                    .position(x: 65.3 * scale, y: 8.9 * scale)
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.839, blue: 0.369))
                    .frame(width: 88 * scale, height: 94 * scale)
                    .position(x: 60 * scale, y: 63 * scale)
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.690, blue: 0.125))
                    .frame(width: 20 * scale, height: 28 * scale)
                    .rotationEffect(.degrees(-18))
                    .position(x: 19.8 * scale, y: 66.2 * scale)
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.690, blue: 0.125))
                    .frame(width: 20 * scale, height: 28 * scale)
                    .rotationEffect(.degrees(18))
                    .position(x: 99.2 * scale, y: 72.4 * scale)
                RoundedRectangle(cornerRadius: 4 * scale)
                    .fill(Color(red: 1.0, green: 0.541, blue: 0.361))
                    .frame(width: 14 * scale, height: 8 * scale)
                    .position(x: 45 * scale, y: 110 * scale)
                RoundedRectangle(cornerRadius: 4 * scale)
                    .fill(Color(red: 1.0, green: 0.541, blue: 0.361))
                    .frame(width: 14 * scale, height: 8 * scale)
                    .position(x: 75 * scale, y: 110 * scale)
                Circle()
                    .fill(PassmateColors.textPrimary)
                    .frame(width: 10 * scale, height: 10 * scale)
                    .position(x: 42 * scale, y: 51 * scale)
                Circle()
                    .fill(PassmateColors.textPrimary)
                    .frame(width: 10 * scale, height: 10 * scale)
                    .position(x: 78 * scale, y: 51 * scale)
                Circle()
                    .fill(PassmateColors.surface)
                    .frame(width: 3 * scale, height: 3 * scale)
                    .position(x: 41.5 * scale, y: 49.5 * scale)
                Circle()
                    .fill(PassmateColors.surface)
                    .frame(width: 3 * scale, height: 3 * scale)
                    .position(x: 77.5 * scale, y: 49.5 * scale)
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.710, blue: 0.710))
                    .frame(width: 12 * scale, height: 8 * scale)
                    .position(x: 34 * scale, y: 66 * scale)
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.710, blue: 0.710))
                    .frame(width: 12 * scale, height: 8 * scale)
                    .position(x: 86 * scale, y: 66 * scale)
                Ellipse()
                    .fill(Color(red: 1.0, green: 0.541, blue: 0.361))
                    .frame(width: 14 * scale, height: 10 * scale)
                    .position(x: 60 * scale, y: 63 * scale)
            }
        }
    }
}
